#!/usr/bin/env bash
# create_issues.sh — Create GitHub Issues from uplevel findings.
#
# @decision Only create issues for HIGH and CRITICAL findings by default.
# MEDIUM findings are included in the report but not as issues to avoid
# noise. Uses finding IDs (e.g., SEC-001) in issue titles for dedup —
# search existing issues before creating to avoid duplicates across runs.
#
# Usage: bash create_issues.sh --report <path> --repo <owner/repo> [--min-severity medium]

set -euo pipefail

# --- Defaults ---
REPORT=""
REPO=""
MIN_SEVERITY="high"
DRY_RUN="false"
LABEL_PREFIX="uplevel"

# --- Arg Parsing ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    --report)     REPORT="$2"; shift 2 ;;
    --repo)       REPO="$2"; shift 2 ;;
    --min-severity) MIN_SEVERITY="$2"; shift 2 ;;
    --dry-run)    DRY_RUN="true"; shift ;;
    *)            echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$REPORT" || -z "$REPO" ]]; then
  echo "Usage: create_issues.sh --report <path> --repo <owner/repo>" >&2
  exit 1
fi

if ! command -v gh &>/dev/null; then
  echo "Error: gh CLI not found. Skipping issue creation." >&2
  exit 0
fi

if ! command -v jq &>/dev/null; then
  echo "Error: jq not found. Skipping issue creation." >&2
  exit 0
fi

if [[ ! -f "$REPORT" ]]; then
  echo "Error: Report not found: $REPORT" >&2
  exit 1
fi

# --- Severity filter ---
severity_rank() {
  case "$1" in
    critical) echo 0 ;;
    high)     echo 1 ;;
    medium)   echo 2 ;;
    low)      echo 3 ;;
    info)     echo 4 ;;
    *)        echo 5 ;;
  esac
}

min_rank=$(severity_rank "$MIN_SEVERITY")

# --- Ensure labels exist ---
ensure_label() {
  local label="$1"
  local color="${2:-ededed}"
  gh label create "$label" --repo "$REPO" --color "$color" --force 2>/dev/null || true
}

echo "Ensuring labels exist..." >&2
ensure_label "$LABEL_PREFIX" "0075ca"
ensure_label "${LABEL_PREFIX}:security" "d73a49"
ensure_label "${LABEL_PREFIX}:testing" "fbca04"
ensure_label "${LABEL_PREFIX}:quality" "a2eeef"
ensure_label "${LABEL_PREFIX}:documentation" "0075ca"
ensure_label "${LABEL_PREFIX}:staleness" "e4e669"
ensure_label "${LABEL_PREFIX}:standards" "d4c5f9"
ensure_label "severity:critical" "b60205"
ensure_label "severity:high" "d93f0b"
ensure_label "severity:medium" "fbca04"
ensure_label "severity:low" "c5def5"

# --- Extract findings and create issues ---
created=0
skipped=0
dupes=0

# Get all findings from the unified report
findings=$(jq -c '.all_findings[]' "$REPORT" 2>/dev/null)

if [[ -z "$findings" ]]; then
  echo "No findings in report." >&2
  exit 0
fi

while IFS= read -r finding; do
  severity=$(echo "$finding" | jq -r '.severity // "info"' | tr '[:upper:]' '[:lower:]')
  finding_rank=$(severity_rank "$severity")

  # Skip findings below minimum severity
  if [[ "$finding_rank" -gt "$min_rank" ]]; then
    ((skipped++)) || true
    continue
  fi

  finding_id=$(echo "$finding" | jq -r '.id // "UNKNOWN"')
  title=$(echo "$finding" | jq -r '.title // "Unknown finding"')
  area=$(echo "$finding" | jq -r '.area // "unknown"')
  description=$(echo "$finding" | jq -r '.description // ""')
  impact=$(echo "$finding" | jq -r '.impact // ""')
  remediation=$(echo "$finding" | jq -r '.remediation // ""')
  effort=$(echo "$finding" | jq -r '.effort // "unknown"')
  location=$(echo "$finding" | jq -r '.location // ""')

  issue_title="[UPLEVEL-${finding_id}] ${title}"

  # Check for existing issue with same finding ID (deduplication)
  existing=$(gh issue list --repo "$REPO" --search "UPLEVEL-${finding_id} in:title" --state open --json number --jq '.[0].number' 2>/dev/null || echo "")

  if [[ -n "$existing" ]]; then
    echo "  Duplicate: ${finding_id} already exists as #${existing}" >&2
    ((dupes++)) || true
    continue
  fi

  # Build issue body
  body="**Severity:** ${severity^^} | **Area:** ${area^} | **Effort:** ${effort}
**Finding ID:** ${finding_id}"

  [[ -n "$location" ]] && body+="
**Location:** ${location}"

  body+="

## What
${description}
"

  if [[ -n "$impact" ]]; then
    body+="
## Why It Matters
${impact}
"
  fi

  if [[ -n "$remediation" ]]; then
    body+="
## How to Fix
${remediation}
"
  fi

  body+="
---
*Generated by \`/uplevel\` — repository health audit*"

  # Labels
  labels="${LABEL_PREFIX},${LABEL_PREFIX}:${area},severity:${severity}"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "  [DRY RUN] Would create: ${issue_title}" >&2
    ((created++)) || true
  else
    gh issue create \
      --repo "$REPO" \
      --title "$issue_title" \
      --body "$body" \
      --label "$labels" \
      2>/dev/null && {
        echo "  Created: ${issue_title}" >&2
        ((created++)) || true
      } || {
        echo "  Failed to create: ${issue_title}" >&2
      }
  fi
done <<< "$findings"

echo "" >&2
echo "Issue creation complete: ${created} created, ${dupes} duplicates skipped, ${skipped} below threshold" >&2
